
// //random generator API////You can use AJAX to call the Random User Generator API and will receive a randomly generated user in return. If you are using jQuery, you can use the $.ajax() function in the code snippet below to get started.
// // $.ajax({
// //   url: 'https://randomuser.me/api/',
// //   dataType: 'json',
// //   success: function(data) {
// //     console.log(data);
// //   }
// // });

// //RESULTS//The API will provide you with a formatted object of your choice that you can parse and apply to your application.

// //JSON is the default format. You can request a different format using the format parameter.
// //}
// //   "results": [
// //     {
// //       "gender": "male",
// //       "name": {
// //         "title": "mr",
// //         "first": "rolf",
// //         "last": "hegdal"
// //       },
// //       "location": {
// //         "street": "ljan terrasse 346",
// //         "city": "vear",
// //         "state": "rogaland",
// //         "postcode": "3095", 
// //       },
// //       "email": "rolf.hegdal@example.com",
// //      
// //       },
// //       "dob": {
// //         "date": "1975-11-12T06:34:44Z",
// //         "age": 42
// //       },
// //       "registered": {
// //         "date": "2015-11-04T22:09:36Z",
// //         "age": 2
// //       },
// //       "phone": "66976498",
// //       "cell": "40652479",
// //       "id": {
// //         "name": "FN",
// //         "value": "12117533881"
// //       },
// //       "picture": {
// //         "large": "https://randomuser.me/api/portraits/men/65.jpg",
// //         "medium": "https://randomuser.me/api/portraits/med/men/65.jpg",
// //         "thumbnail": "https://randomuser.me/api/portraits/thumb/men/65.jpg"
// //       },
// //       "nat": "NO"
// //     }
// //   ],
// //   "info": {
// //     "seed": "2da87e9305069f1d",
// //     "results": 1,
// //     "page": 1,
// //     "version": "1.2"
// //   }
// // }


// //REUESTING MULTIPLE USERS//Random User Generator allows you to fetch up to 5,000 generated users in one request using the results parameter.
// //https://randomuser.me/api/?results=5000

// //You can specify whether you would like to have only male or only female users generated by adding the gender parameter to your request. Valid values for the gender parameter are "male" or "female", or you may leave the parameter blank. Any other value will cause the service to return both male and female users.

// //https://randomuser.me/api/?gender=female

// /*We currently offer the following data formats:

// JSON (default)    ////use this
// PrettyJSON or pretty
// CSV
// YAML
// XML
// Just specify the format you would like returned by using the format parameter.*/
// //https://randomuser.me/api/?format=JSON

// /*Including/Excluding fields
// Sometimes, maybe you want some random names and not extraneous data such as location, phone, etc.
// Using the inc and exc parameters, you can specify which fields to include or exclude respectively.

// By specifying only the fields you want, the generator can save time by skipping CPU intensive fields like "login" for example.

// These parameters accept the following values in a comma delimited list

// gender       //use this
// name         // use this
// location     // use this
// email        // use this
// login
// registered
// dob          //use this
// phone        //use this
// cell
// id
// picture      //use this
// nat          // use this? 

// If you only wanted the names,genders,and nats of users:
// https://randomuser.me/api/?inc=gender,name,nat.location,email,dob,phone,picture


// If you want everything except for login data:
// https://randomuser.me/api/?exc=login,registered,cell,id
// */









// //////////creating the thumbnail images with overlay///////////
// // const current = document.querySelector("#current");
// // const imgs = document.querySelectorAll(".imgs img");
// // const opacity = 0.6;

// // // Set first img opacity
// // imgs[0].style.opacity = opacity;

// // imgs.forEach(img => img.addEventListener("click", imgClick));

// // function imgClick(e) {
// //   // Reset the opacity
// //   imgs.forEach(img => (img.style.opacity = 1));

// //   // Change current image to src of clicked image
// //   current.src = e.target.src;

// //   // Add fade in class
// //   current.classList.add("fade-in");

// //   // Remove fade-in class after .5 seconds
// //   setTimeout(() => current.classList.remove("fade-in"), 500);

// //   // Change the opacity to opacity var
// //   e.target.style.opacity = opacity;
// // }



/////////////////////////////modal/////////////////////////////////
// Get modal element
var modal = document.getElementById('simpleModal');
// Get open modal button
var modalBtn = document.getElementById('modalBtn');
// Get close button
var closeBtn = document.getElementsByClassName('closeBtn')[0];

// Listen for open click
modalBtn.addEventListener('click', openModal);
// Listen for close click
closeBtn.addEventListener('click', closeModal);
// Listen for outside click
window.addEventListener('click', outsideClick);

// Function to open modal
function openModal(){
  modal.style.display = 'block';
}

// Function to close modal
function closeModal(){
  modal.style.display = 'none';
}

// Function to close modal if outside click
function outsideClick(e){
  if(e.target == modal){
    modal.style.display = 'none';
  }
}



